version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tokenizer
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tokenizer_db
    ports:
      - "3306:3306"

  tokenizer:
    build: .
    container_name: tokenizer-service
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tokenizer_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
